import 'package:flutter/material.dart';

List festlist = [
  {
    'Festival': 'Diwali',
    'word': 'Create your Diwali Templates',
    'Image': 'assets/Diwali/img_2.1.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/Diwali/img_2.1.jpg',
      'assets/Diwali/img_2.2.jpg',
      'assets/Diwali/img_2.3.jpg',
      'assets/Diwali/img_2.4.jpg',
      'assets/Diwali/img_2.5.jpg',
    ],
  },
  {
    'Festival': 'Pongal',
    'word': 'Create your Pongal Templates',
    'Image': 'assets/pogal/img1.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/pogal/img1.jpg',
      'assets/pogal/img2.jpg',
      'assets/pogal/img3.jpg',
      'assets/pogal/img4.jpg',
      'assets/pogal/img5.jpg',
    ],
  },
  {
    'Festival': 'Raksha Bandhan',
    'word': 'Create your Raksha Bandhan Templates',
    'Image': 'assets/raksha_bandhan/img_3.1.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/raksha_bandhan/img_3.1.jpg',
      'assets/raksha_bandhan/img_3.2.jpg',
      'assets/raksha_bandhan/img_3.3.jpg',
      'assets/raksha_bandhan/img_3.4.jpg',
      'assets/raksha_bandhan/img_3.5.jpg',
    ],
  },
  {
    'Festival': 'Makar Sakranti',
    'word': 'Create your Makar Sakranti Templates',
    'Image': 'assets/maker_sankrti/img_4.1_cleanup.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/maker_sankrti/img_4.1_cleanup.jpg',
      'assets/maker_sankrti/img_4.2_cleanup.jpg',
      'assets/maker_sankrti/img_4.3_cleanup.jpg',
      'assets/maker_sankrti/img_4.4.jpg',
      'assets/maker_sankrti/img_4.5.jpg',
    ],
  },
  {
    'Festival': 'Basant Panchami',
    'word': 'Create your Basant Panchami Templates',
    'Image': 'assets/Basnt_panchami/img1.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/Basnt_panchami/img1.jpg',
      'assets/Basnt_panchami/img2.jpg',
      'assets/Basnt_panchami/img3.jpg',
      'assets/Basnt_panchami/img4.jpg',
      'assets/Basnt_panchami/img5.jpg',
    ],
  },
  {
    'Festival': 'Maha Shivratri',
    'word': 'Create your Maha Shivratri Templates',
    'Image': 'assets/maha_shivratri/img1.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/maha_shivratri/img1.jpg',
      'assets/maha_shivratri/img2.jpg',
      'assets/maha_shivratri/img3.jpg',
      'assets/maha_shivratri/img4.jpg',
      'assets/maha_shivratri/img5.jpg',
    ],
  },
  {
    'Festival': 'Holi',
    'word': 'Create your holi Templates',
    'Image': 'assets/holi/img_5.1.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/holi/img_5.1.jpg',
      'assets/holi/img_5.2.jpg',
      'assets/holi/img_5.3.jpg',
      'assets/holi/img_5.4.jpg',
      'assets/holi/img_5.5.jpg',
    ],
  },
  {
    'Festival': 'Navratri',
    'word': 'Create your Navratri Templates',
    'Image': 'assets/navratri/img1.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/navratri/img1.jpg',
      'assets/navratri/img2.jpg',
      'assets/navratri/img3.jpg',
      'assets/navratri/img4.jpg',
      'assets/navratri/img5.jpg',
    ],
  },
  {
    'Festival': 'Bhai dhuj',
    'word': 'Create your Bhai dhuj Templates',
    'Image': 'assets/bhai_dooj/img1.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/bhai_dooj/img1.jpg',
      'assets/bhai_dooj/img2.jpg',
      'assets/bhai_dooj/img3.jpg',
      'assets/bhai_dooj/img4.jpg',
      'assets/bhai_dooj/img5.jpg',
    ],
  },
  {
    'Festival': 'Ganesh Chaturthi',
    'word': 'Create your Ganesh Chaturthi Templates',
    'Image': 'assets/genesh_chaturtiy/img_1.1.png',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/genesh_chaturtiy/img_1.1.png',
      'assets/genesh_chaturtiy/img_1.2.png',
      'assets/genesh_chaturtiy/img_1.3.png',
      'assets/genesh_chaturtiy/img_1.4.png',
      'assets/genesh_chaturtiy/img_1.5.png',
    ],
  },
  {
    'Festival': 'Independence Day',
    'word': 'Create your Independence Day Templates',
    'Image': 'assets/indpened_day/day_cleanup.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/indpened_day/day_cleanup.jpg',
      'assets/indpened_day/img1_cleanup.jpg',
      'assets/indpened_day/img2_cleanup.jpg',
      'assets/indpened_day/img3_cleanup.jpg',
      'assets/indpened_day/img4_cleanup.jpg',
    ],
  },
  {
    'Festival': 'Republic Day',
    'word': 'Create your Republic Day Templates',
    'Image': 'assets/republic_day/img1_cleanup.jpg',
    'Color': Color(0xff1E456C),
    'images': [
      'assets/republic_day/img1_cleanup.jpg',
      'assets/republic_day/img2_cleanup.jpg',
      'assets/republic_day/img3_cleanup.jpg',
      'assets/republic_day/img4_cleanup.jpg',
      'assets/republic_day/img5_cleanup.jpg',
    ],
  },
];
